import "./globals.css";
import type { Metadata } from "next";
import type { Layout } from "@/types/Layout";
import { geistSans, geistMono } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Mood",
  description: "Generated by create next app",
};

function RootLayout({ children }: Layout) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
